/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculadora_constants.h"



const calculadoraConstants g_calculadora_constants;

calculadoraConstants::calculadoraConstants() {
}



