/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculadora_CONSTANTS_H
#define calculadora_CONSTANTS_H

#include "calculadora_types.h"



class calculadoraConstants {
 public:
  calculadoraConstants();

};

extern const calculadoraConstants g_calculadora_constants;



#endif
