/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_vec (XDR *xdrs, vec *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vec_val, (u_int *) &objp->vec_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_polinomio (XDR *xdrs, polinomio *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->polinomio_val, (u_int *) &objp->polinomio_len, ~0,
		sizeof (struct operacion), (xdrproc_t) xdr_operacion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion (XDR *xdrs, operacion *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->val))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->op_izq))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->op_dcha))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculadora_res (XDR *xdrs, calculadora_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_double (xdrs, &objp->calculadora_res_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_calculadora_res_vec (XDR *xdrs, calculadora_res_vec *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vec (xdrs, &objp->calculadora_res_vec_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_suma_1_argument (XDR *xdrs, suma_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_1_argument (XDR *xdrs, resta_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacion_1_argument (XDR *xdrs, multiplicacion_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_division_1_argument (XDR *xdrs, division_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumavec_1_argument (XDR *xdrs, sumavec_1_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restavec_1_argument (XDR *xdrs, restavec_1_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacionvec_1_argument (XDR *xdrs, multiplicacionvec_1_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacionvec_esc_1_argument (XDR *xdrs, multiplicacionvec_esc_1_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
