/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

calculadora_res *
suma_1(double arg1, double arg2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static calculadora_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, SUMA, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res *
resta_1(double arg1, double arg2,  CLIENT *clnt)
{
	resta_1_argument arg;
	static calculadora_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, RESTA, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res *
multiplicacion_1(double arg1, double arg2,  CLIENT *clnt)
{
	multiplicacion_1_argument arg;
	static calculadora_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, MULTIPLICACION, (xdrproc_t) xdr_multiplicacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res *
division_1(double arg1, double arg2,  CLIENT *clnt)
{
	division_1_argument arg;
	static calculadora_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, DIVISION, (xdrproc_t) xdr_division_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res_vec *
sumavec_1(vec arg1, vec arg2,  CLIENT *clnt)
{
	sumavec_1_argument arg;
	static calculadora_res_vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, SUMAVEC, (xdrproc_t) xdr_sumavec_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res_vec *
restavec_1(vec arg1, vec arg2,  CLIENT *clnt)
{
	restavec_1_argument arg;
	static calculadora_res_vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, RESTAVEC, (xdrproc_t) xdr_restavec_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res_vec *
multiplicacionvec_1(vec arg1, vec arg2,  CLIENT *clnt)
{
	multiplicacionvec_1_argument arg;
	static calculadora_res_vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, MULTIPLICACIONVEC, (xdrproc_t) xdr_multiplicacionvec_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res_vec *
multiplicacionvec_esc_1(vec arg1, double arg2,  CLIENT *clnt)
{
	multiplicacionvec_esc_1_argument arg;
	static calculadora_res_vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, MULTIPLICACIONVEC_ESC, (xdrproc_t) xdr_multiplicacionvec_esc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculadora_res_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calculadora_res *
polinomio_1(polinomio arg1,  CLIENT *clnt)
{
	static calculadora_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, POLINOMIO,
		(xdrproc_t) xdr_polinomio, (caddr_t) &arg1,
		(xdrproc_t) xdr_calculadora_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
