/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static calculadora_res *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res_vec *
_sumavec_1 (sumavec_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavec_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res_vec *
_restavec_1 (restavec_1_argument *argp, struct svc_req *rqstp)
{
	return (restavec_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res_vec *
_multiplicacionvec_1 (multiplicacionvec_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacionvec_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res_vec *
_multiplicacionvec_esc_1 (multiplicacionvec_esc_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacionvec_esc_1_svc(argp->arg1, argp->arg2, rqstp));
}

static calculadora_res *
_polinomio_1 (polinomio  *argp, struct svc_req *rqstp)
{
	return (polinomio_1_svc(*argp, rqstp));
}

static void
calcprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		sumavec_1_argument sumavec_1_arg;
		restavec_1_argument restavec_1_arg;
		multiplicacionvec_1_argument multiplicacionvec_1_arg;
		multiplicacionvec_esc_1_argument multiplicacionvec_esc_1_arg;
		polinomio polinomio_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case SUMAVEC:
		_xdr_argument = (xdrproc_t) xdr_sumavec_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res_vec;
		local = (char *(*)(char *, struct svc_req *)) _sumavec_1;
		break;

	case RESTAVEC:
		_xdr_argument = (xdrproc_t) xdr_restavec_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res_vec;
		local = (char *(*)(char *, struct svc_req *)) _restavec_1;
		break;

	case MULTIPLICACIONVEC:
		_xdr_argument = (xdrproc_t) xdr_multiplicacionvec_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res_vec;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacionvec_1;
		break;

	case MULTIPLICACIONVEC_ESC:
		_xdr_argument = (xdrproc_t) xdr_multiplicacionvec_esc_1_argument;
		_xdr_result = (xdrproc_t) xdr_calculadora_res_vec;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacionvec_esc_1;
		break;

	case POLINOMIO:
		_xdr_argument = (xdrproc_t) xdr_polinomio;
		_xdr_result = (xdrproc_t) xdr_calculadora_res;
		local = (char *(*)(char *, struct svc_req *)) _polinomio_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCPROG, CALCVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCPROG, CALCVER, calcprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCPROG, CALCVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCPROG, CALCVER, calcprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCPROG, CALCVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
