#
# Autogenerated by Thrift Compiler (0.14.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class operacion(object):
    """
    Attributes:
     - val
     - op_izq
     - op_dcha

    """


    def __init__(self, val=None, op_izq=None, op_dcha=None,):
        self.val = val
        self.op_izq = op_izq
        self.op_dcha = op_dcha

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.val = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.op_izq = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.op_dcha = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('operacion')
        if self.val is not None:
            oprot.writeFieldBegin('val', TType.DOUBLE, 1)
            oprot.writeDouble(self.val)
            oprot.writeFieldEnd()
        if self.op_izq is not None:
            oprot.writeFieldBegin('op_izq', TType.STRING, 2)
            oprot.writeString(self.op_izq.encode('utf-8') if sys.version_info[0] == 2 else self.op_izq)
            oprot.writeFieldEnd()
        if self.op_dcha is not None:
            oprot.writeFieldBegin('op_dcha', TType.STRING, 3)
            oprot.writeString(self.op_dcha.encode('utf-8') if sys.version_info[0] == 2 else self.op_dcha)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.val is None:
            raise TProtocolException(message='Required field val is unset!')
        if self.op_izq is None:
            raise TProtocolException(message='Required field op_izq is unset!')
        if self.op_dcha is None:
            raise TProtocolException(message='Required field op_dcha is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(operacion)
operacion.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'val', None, None, ),  # 1
    (2, TType.STRING, 'op_izq', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'op_dcha', 'UTF8', None, ),  # 3
)
fix_spec(all_structs)
del all_structs
