/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include <dirent.h>
#include <errno.h>

//extern int errno;

readdir_res * readdir_1_svc(nametype dirname,  struct svc_req *rqstp) {

	DIR *dirp;
	struct dirent *d;
	namelist nl;
	namelist *nlp;

	static readdir_res result;
	dirp = opendir(dirname);

	if (dirp == (DIR *)NULL) {
		result.err = errno;
		return (&result);
	}

	/*
	 * La siguiente linea de codigo libera la memoria que se asigno * (para el resultado) en una ejecucion previa del servidor
	 */
	xdr_free(xdr_readdir_res, &result);

	nlp = &result.readdir_res_u.list;
	while (d = readdir(dirp)) {
		nl = *nlp = (namenode *) malloc(sizeof(namenode));
		if (nl == (namenode *) NULL) {
			result.err = 10;
			closedir(dirp);
			return (&result);
		}
		nl->name = strdup(d->d_name);
		nlp = &nl->next;
	}
	*nlp = (namelist)NULL;
	result.err = 0;
	closedir (dirp);
	return (&result);
}

/* Compilar con:
	gcc dir_server.c dir_svc.c dir_xdr.c -o servidor -lnsl -ltirpc
	gcc dir_client.c dir_clnt.c dir_xdr.c -o cliente -lnsl -ltirpc
*/
